// Latin Roots: a Flashcard Deck (Learn + Quiz). Each card is a glossary
// entry (standard-deck/glossary.js): its forms on the front, its meanings
// (one per line) and examples on the back. In the quiz the student types
// the meanings one per line and every meaning is required; each meaning has
// its own key-word list. Key-word lists approved by the instructor on
// Oct 5, 2026 (proposals/latin-roots-keyword-lists.md). A wording listed on
// more than one card never counts against an answer on either card.
const SEE=["see","sight","vision"], STRONG=["strong","strength","sturdy","mighty","powerful"],
 GO=["go","move","proceed"], PUSH=["push","shove","press"], HOLY=["holy","holiness","hallowed"],
 AROUND=["around","round","about","surrounding"], BEFORE=["before","prior","earlier","previous","preceding"],
 NOT=["not","no","non","un"], AWAY=["away","off"], AGAINST=["against","opposed","opposing","opposite","versus","contrary"],
 TOWARD=["toward","towards","in the direction of"], BELOW=["below","lower","underneath"], WITHOUT=["without","lacking","lack"],
 APART=["apart","separate","asunder"], THROUGH=["through","throughout"], BEYOND=["beyond","more than","further","past"],
 FROM=["from"];

module.exports = {
  id: "latinroots",
  output: "index.html",
  title: "Latin Roots Flashcards", // deck name sent to the Sheet
  heading: "Latin Roots",
  answer: "meanings",
  quizBySet: true,
  noun: "card",
  backLabel: "Examples",
  quizIntro: "Type every meaning of each base or prefix, one per line. Tap “+ Add another meaning” (or press Enter) for each new line.",
  categories: [
    { key: "base", label: "Bases" },
    { key: "prefix", label: "Prefixes" }
  ],
  legacy: { knownPrefix: "latinFlashcards_known_v2__", learningPrefix: "latinFlashcards_learning_v2__", nameKey: "latinFlashcards_lastName" },
  cards: [
    { gloss: "ALIEN", cat: "base", keys: [["belonging to another","another's","someone else's","another","other"],["foreign","foreigner","strange","stranger","alien"]] },
    { gloss: "ART", cat: "base", keys: [["skill","skilled","skillful","art","talent","technique"],["craft","craftsmanship","handiwork","artistry"]] },
    { gloss: "CED", cat: "base", keys: [GO,["yield","give way","give in","surrender","concede","submit"],["withdraw","retreat","pull back","back away","recede"]] },
    { gloss: "CLUD", cat: "base", keys: [["close","closed","enclose"],["shut","shut in","shut out","lock","seal"]] },
    { gloss: "CRUC", cat: "base", keys: [["cross","crucifix"]] },
    { gloss: "CUR", cat: "base", keys: [["run","running","race","rush","dash","sprint"]] },
    { gloss: "DUC", cat: "base", keys: [["lead","leader","guide","conduct","bring"]] },
    { gloss: "FAC", cat: "base", keys: [["make","create","build","form","produce"],["do","act","perform","carry out"]] },
    { gloss: "FIN", cat: "base", keys: [["end","finish","final","ending"],["boundary","border","limit","edge","bound"]] },
    { gloss: "FIRM", cat: "base", keys: [STRONG,["firm","steady","stable","solid","secure","fixed"]] },
    { gloss: "FORT", cat: "base", keys: [STRONG,["brave","bravery","courage","courageous","bold","valiant","fearless"]] },
    { gloss: "GRAD", cat: "base", keys: [["step","stage","degree","grade"],GO,["walk","march","stride"]] },
    { gloss: "GRAND", cat: "base", keys: [["great","grand","magnificent"],["large","big","huge","vast"]] },
    { gloss: "GRAV", cat: "base", keys: [["heavy","heaviness","serious","grave","burdensome"]] },
    { gloss: "GREG", cat: "base", keys: [["flock","herd"],["group","crowd","gathering","gather","assembly","band"]] },
    { gloss: "HAB", cat: "base", keys: [["have","own","possess","possession"],["hold","keep","contain","grasp"]] },
    { gloss: "JUDIC", cat: "base", keys: [["judge","judgment","judgement","decide","assess"]] },
    { gloss: "JUR", cat: "base", keys: [["law","legal","lawful"],["right","just","justice","fair","rightful"],["swear","oath","vow","pledge"]] },
    { gloss: "LEV", cat: "base", keys: [["light","lightness","light in weight","weightless"],["lift","raise","rise","elevate"]] },
    { gloss: "LINE", cat: "base", keys: [["line","row","stroke"],["thread","string","cord","yarn","strand"]] },
    { gloss: "LIMIN", cat: "base", keys: [["threshold","doorway","entrance","doorstep","sill"]] },
    { gloss: "LOC", cat: "base", keys: [["place","location","spot","site","position"]] },
    { gloss: "LOQU", cat: "base", keys: [["speak","speech","say","utter"],["talk","chat","converse","conversation"]] },
    { gloss: "LUD", cat: "base", keys: [["play","game","playful","mock","joke","sport"]] },
    { gloss: "NIHIL", cat: "base", keys: [["nothing","nothingness","void","zero"]] },
    { gloss: "NOMIN", cat: "base", keys: [["name","naming","title","noun"]] },
    { gloss: "NUL", cat: "base", keys: [["none","null","no one"],["not any","nil"]] },
    { gloss: "PART", cat: "base", keys: [["part","piece","portion","section","fraction"],["share","divide","division","participate"]] },
    { gloss: "PED", cat: "base", keys: [["foot","feet"]] },
    { gloss: "PEND", cat: "base", keys: [["hang","hanging","suspend","dangle"],["weigh","weighing","balance"],["pay","payment","spend","expend","compensate"]] },
    { gloss: "PLE", cat: "base", keys: [["fill","filling","fill up","supply"],["full","fullness","complete","plenty","plentiful"]] },
    { gloss: "PREC", cat: "base", keys: [["pray","prayer"],["ask","request","entreat"],["beg","plead","implore","beseech"]] },
    { gloss: "PULS", cat: "base", keys: [["drive","drive out","propel","force"],PUSH,["beat","beating","strike","hit","throb","pulse"]] },
    { gloss: "PUNG", cat: "base", keys: [["prick","sting","jab"],["pierce","puncture","perforate","stab"],["point","dot","tip","sharp"]] },
    { gloss: "SACR", cat: "base", keys: [["sacred","consecrated","divine","blessed","religious"],HOLY] },
    { gloss: "SANCT", cat: "base", keys: [HOLY.concat(["sacred"]),["inviolable","untouchable","sacrosanct","protected"]] },
    { gloss: "SED", cat: "base", keys: [["sit","seat","seated"],["settle","settle down","sink","rest","remain"]] },
    { gloss: "SENT", cat: "base", keys: [["feel","feeling","emotion","emotional"],["perceive","perception","sense","notice","detect","be aware"]] },
    { gloss: "SPEC", cat: "base", keys: [["look","look at","watch","observe","view"],SEE] },
    { gloss: "SPIR", cat: "base", keys: [["breathe","breath","respire","inhale","exhale"]] },
    { gloss: "TRUD", cat: "base", keys: [PUSH,["thrust","plunge"]] },
    { gloss: "TURB", cat: "base", keys: [["disturb","disturbance","upset","agitate","stir","unsettle"],["confuse","confusion","bewilder","mix up","disorder"],["crowd","throng","mob","multitude"]] },
    { gloss: "UND", cat: "base", keys: [["wave","surge","billow","ripple"]] },
    { gloss: "VEN", cat: "base", keys: [["come","coming","arrive","approach"]] },
    { gloss: "VERB", cat: "base", keys: [["word","wording"]] },
    { gloss: "VERT", cat: "base", keys: [["turn","rotate","spin","revolve"]] },
    { gloss: "VEST", cat: "base", keys: [["clothing","clothes","clothe","garment","dress","attire","robe","vestment"]] },
    { gloss: "VI", cat: "base", keys: [["way","path","route"],["road","street","highway"]] },
    { gloss: "VID", cat: "base", keys: [SEE.concat(["view","observe"])] },
    { gloss: "VOC", cat: "base", keys: [["call","calling","summon","cry out"],["voice","vocal","sound"]] },
    { gloss: "AB", cat: "prefix", keys: [["away from","away","off"],FROM] },
    { gloss: "AD", cat: "prefix", keys: [["to","at"],TOWARD] },
    { gloss: "AMBI", cat: "prefix", keys: [["both","two","double","two sides"],AROUND] },
    { gloss: "ANTE", cat: "prefix", keys: [BEFORE] },
    { gloss: "CIRCUM", cat: "prefix", keys: [AROUND] },
    { gloss: "CON", cat: "prefix", keys: [["with","along with"],["together","joint","jointly","united","union"]] },
    { gloss: "CONTRA", cat: "prefix", keys: [AGAINST] },
    { gloss: "DE", cat: "prefix", keys: [["down","downward","descend"],AWAY,["reversal","reverse","undo","remove","removal"]] },
    { gloss: "DIS", cat: "prefix", keys: [APART.concat(["in different directions"]),NOT,AWAY] },
    { gloss: "EX", cat: "prefix", keys: [["out","outward","exit"],["out of","from"]] },
    { gloss: "EXTRA", cat: "prefix", keys: [["outside","outer","external"],BEYOND] },
    { gloss: "IN-not", cat: "prefix", keys: [NOT,WITHOUT] },
    { gloss: "IN-into", cat: "prefix", keys: [["into"],["in"],["on","onto"],["upon"]] },
    { gloss: "INFRA", cat: "prefix", keys: [BELOW.concat(["under"]),["beneath"]] },
    { gloss: "INTER", cat: "prefix", keys: [["between","in between"],["among","amongst","amid"]] },
    { gloss: "INTRA", cat: "prefix", keys: [["within"],["inside","internal","inner","interior"]] },
    { gloss: "NON", cat: "prefix", keys: [NOT] },
    { gloss: "OB", cat: "prefix", keys: [AGAINST,TOWARD,["in the way","blocking","block","obstruct","hinder"]] },
    { gloss: "PER", cat: "prefix", keys: [THROUGH,["thoroughly","thorough","entirely","very"]] },
    { gloss: "POST", cat: "prefix", keys: [["after","behind","later","afterward","following"]] },
    { gloss: "PRE", cat: "prefix", keys: [BEFORE] },
    { gloss: "PRO", cat: "prefix", keys: [["forward","forth","ahead","onward"],["for"],["in favor of","in favour of","favor","favoring","support","supporting"]] },
    { gloss: "RE", cat: "prefix", keys: [["back","return"],["again","anew","repeat","once more"]] },
    { gloss: "RETRO", cat: "prefix", keys: [["backward","backwards","back"]] },
    { gloss: "SE", cat: "prefix", keys: [APART,["aside","to one side"],WITHOUT] },
    { gloss: "SUB", cat: "prefix", keys: [["under"],BELOW] },
    { gloss: "SUPER", cat: "prefix", keys: [["above","higher","superior","on top"],["over"]] },
    { gloss: "TRANS", cat: "prefix", keys: [["across","cross","crossing","to the other side"],THROUGH,BEYOND] },
    { gloss: "ULTRA", cat: "prefix", keys: [BEYOND,["excessively","excessive","too","too much","extreme","extremely"]] }
  ]
};
