// Lesson IX Workbook: an Exercise Deck (Quiz mode only).
// Content verified against Ayers, Part I, Lesson IX workbook (pp. 51-56),
// copied unchanged from the earlier self-graded deck.
// Card kinds: "choice" (tap one option; answer = its index) and "typed"
// (type the word or base; accept = the answers that count, compared without
// case, accents, hyphens or brackets). A typed card with "gloss" takes its
// accepted answers and its meaning from that shared glossary entry.
// Cards about one word name it in the shared vocabulary list (vocab); the
// card keeps everything the exercise shows, so the list only records the word.
module.exports = {
  id: "l9",
  type: "exercise",
  output: "Lesson IX Workbook Flashcards.html",
  title: "Lesson IX Workbook Flashcards", // deck name sent to the Sheet (unchanged)
  heading: "Lesson IX Workbook",
  round1: "book", // Round 1 in the workbook's order; later rounds shuffled
  legacy: { progressKey: "l9_progress", nameKey: "l9_name" },
  categories: [
    { key: "1", label: "Ex 1", title: "Exercise 1: Word Analysis", instruction: "Identify the correct analysis (prefix or combining form / base)." },
    { key: "2", label: "Ex 2", title: "Exercise 2: Words of Interest", instruction: "Supply the appropriate word from the bank below.",
      bank: ["afflatus","collateral","dessert","dome","domino","dungeon","engine","flagrant","flamboyant","flamenco","flamingo","ingenuity","limn","Lucifer","parade","penitentiary","several","soufflé"] },
    { key: "3", label: "Ex 3", title: "Exercise 3: Matching", instruction: "Match the word with its best definition.", baseLine: "DOM(IN)-; FLAG(R)-, FLAM(M)-; LUC-, LUMIN-; PAR-; SEN-; SERV-",
      options: ["a large, destructive fire","attire","to assist in a minor capacity","self-restrained","priority gained through length of service","place of residence","to deflect; to evade","to enlighten","to remove by cutting","realm","prevailing","slavery","old age","a purchased apartment","clear"], optionStyle: "letters" },
    { key: "4", label: "Ex 4", title: "Exercise 4: True or False", instruction: "Decide whether the statement is true or false." },
    { key: "5", label: "Ex 5", title: "Exercise 5: Matching", instruction: "Match the word with its best definition.", baseLine: "GEN-, GENER-; GEN-",
      options: ["agreeable","offspring; descendant","to begin to grow; to sprout","selfish","unselfish","mild","an artless, innocent young girl","existing at birth","classification as to sex","capable of being produced","category of artistic composition","goods sold by type or kind, not by brand name","to produce anew","to make universal or indefinite","the science of heredity","insincere; calculating","authentic"], optionStyle: "letters" },
    { key: "6", label: "Ex 6", title: "Exercise 6: The French Connection", instruction: "These words entered English through French \u2014 name the base." },
    { key: "7", label: "Ex 7", title: "Exercise 7: The Odd One Out", instruction: "Pick the one word that does NOT belong." }
  ],
  cards: [
    { vocab: "biped", cat: "1", kind: "choice", word: "biped", options: ["two, twice / part","good, well / foot","good, well / part","two, twice / foot"], optionStyle: "paren", answer: 3 },
    { vocab: "introversive", cat: "1", kind: "choice", word: "introversive", options: ["between / to turn","between / voice, to call","within / to turn","within / voice, to call"], optionStyle: "paren", answer: 2 },
    { vocab: "recessive", cat: "1", kind: "choice", word: "recessive", options: ["out, from / to go, to yield","out, from / to run, to go","back, again / to go, to yield","back, again / to run, to go"], optionStyle: "paren", answer: 2 },
    { vocab: "unanimous", cat: "1", kind: "choice", word: "unanimous", options: ["one / mind, feeling, life","not / year","one / year","not / mind, feeling, life"], optionStyle: "paren", answer: 0 },
    { vocab: "discursive", cat: "1", kind: "choice", word: "discursive", options: ["to, toward / cure, care","to, toward / to run, go","in different directions / cure, care","in different directions / to run, go"], optionStyle: "paren", answer: 3 },
    { vocab: "devious", cat: "1", kind: "choice", word: "devious", options: ["down, off / to see","down, off / way, road","through / to see","through / way, road"], optionStyle: "paren", answer: 1 },
    { vocab: "prospective", cat: "1", kind: "choice", word: "prospective", options: ["through / sacred","forward, for / to look","forward, for / sacred","through / to look"], optionStyle: "paren", answer: 1 },
    { vocab: "complementary", cat: "1", kind: "choice", word: "complementary", options: ["against / to fill","against / to fold, to tangle","with, together / to fold, to tangle","with, together / to fill"], optionStyle: "paren", answer: 3 },
    { vocab: "prelusory", cat: "1", kind: "choice", word: "prelusory", options: ["before / to play, to mock","before / to shut","through / to shut","through / to play, to mock"], optionStyle: "paren", answer: 0 },
    { vocab: "evidential", cat: "1", kind: "choice", word: "evidential", options: ["forward / way, road","forward / to see","out, from / way, road","out, from / to see"], optionStyle: "paren", answer: 3 },
    { vocab: "circumlocutory", cat: "1", kind: "choice", word: "circumlocutory", options: ["with / to play, to mock","around / to play, to mock","with / to speak","around / to speak"], optionStyle: "paren", answer: 3 },
    { vocab: "superannuated", cat: "1", kind: "choice", word: "superannuated", options: ["over, above / year","under, below / year","over, above / mind, feeling, life","under, below / mind, feeling, life"], optionStyle: "paren", answer: 0 },
    { vocab: "engine", cat: "2", kind: "typed", label: "engine", lines: [["Etymological meaning","clever invention"],["Current meaning","locomotive; motor"]], accept: ["engine"], answerText: "engine", placeholder: "Type the word" },
    { vocab: "domino", cat: "2", kind: "typed", label: "domino", lines: [["Etymological meaning","a monastic hood"],["Current meaning","a game-piece with spots"]], accept: ["domino"], answerText: "domino", placeholder: "Type the word" },
    { vocab: "dessert", cat: "2", kind: "typed", label: "dessert", lines: [["Etymological meaning","removal of the dishes"],["Current meaning","last course of a meal"]], accept: ["dessert"], answerText: "dessert", placeholder: "Type the word" },
    { vocab: "parade", cat: "2", kind: "typed", label: "parade", lines: [["Etymological meaning","a stopping place"],["Current meaning","a public promenade"]], accept: ["parade"], answerText: "parade", placeholder: "Type the word" },
    { vocab: "afflatus", cat: "2", kind: "typed", label: "afflatus", lines: [["Etymological meaning","a breathing upon"],["Current meaning","divine inspiration"]], accept: ["afflatus"], answerText: "afflatus", placeholder: "Type the word" },
    { vocab: "Lucifer", cat: "2", kind: "typed", label: "Lucifer", lines: [["Etymological meaning","the light-bearer"],["Current meaning","Satan"]], accept: ["Lucifer"], answerText: "Lucifer", placeholder: "Type the word" },
    { vocab: "flamingo", cat: "2", kind: "typed", label: "flamingo", lines: [["Etymological meaning","flame"],["Current meaning","a large, wading bird"]], accept: ["flamingo"], answerText: "flamingo", placeholder: "Type the word" },
    { vocab: "dungeon", cat: "2", kind: "typed", label: "dungeon", lines: [["Etymological meaning","mastery"],["Current meaning","a prison"]], accept: ["dungeon"], answerText: "dungeon", placeholder: "Type the word" },
    { vocab: "soufflé", cat: "2", kind: "typed", label: "soufflé", lines: [["Etymological meaning","puffed up"],["Current meaning","a baked dish made of eggs"]], accept: ["soufflé"], answerText: "soufflé", placeholder: "Type the word" },
    { vocab: "dome", cat: "2", kind: "typed", label: "dome", lines: [["Etymological meaning","a house"],["Current meaning","hemispherical roof"]], accept: ["dome"], answerText: "dome", placeholder: "Type the word" },
    { vocab: "flagrant", cat: "2", kind: "typed", label: "flagrant", lines: [["Etymological meaning","blazing"],["Current meaning","shocking; notorious"]], accept: ["flagrant"], answerText: "flagrant", placeholder: "Type the word" },
    { vocab: "limn", cat: "2", kind: "typed", label: "limn", lines: [["Etymological meaning","to illuminate manuscripts"],["Current meaning","to depict"]], accept: ["limn"], answerText: "limn", placeholder: "Type the word" },
    { vocab: "flamboyant", cat: "2", kind: "typed", label: "flamboyant", lines: [["Etymological meaning","having flame-like curves"],["Current meaning","highly ornate"]], accept: ["flamboyant"], answerText: "flamboyant", placeholder: "Type the word" },
    { vocab: "collateral", cat: "2", kind: "typed", label: "collateral", lines: [["Etymological meaning","side by side"],["Current meaning","security for a loan"]], accept: ["collateral"], answerText: "collateral", placeholder: "Type the word" },
    { vocab: "several", cat: "2", kind: "typed", label: "several", lines: [["Etymological meaning","separated"],["Current meaning","more than a few"]], accept: ["several"], answerText: "several", placeholder: "Type the word" },
    { vocab: "condominium", cat: "3", kind: "choice", word: "condominium", ask: "Which definition matches?", answer: 13 },
    { vocab: "dominant", cat: "3", kind: "choice", word: "dominant", ask: "Which definition matches?", answer: 10 },
    { vocab: "domain", cat: "3", kind: "choice", word: "domain", ask: "Which definition matches?", answer: 9 },
    { vocab: "domicile", cat: "3", kind: "choice", word: "domicile", ask: "Which definition matches?", answer: 5 },
    { vocab: "conflagration", cat: "3", kind: "choice", word: "conflagration", ask: "Which definition matches?", answer: 0 },
    { vocab: "illuminate", cat: "3", kind: "choice", word: "illuminate", ask: "Which definition matches?", answer: 7 },
    { vocab: "pellucid", cat: "3", kind: "choice", word: "pellucid", ask: "Which definition matches?", answer: 14 },
    { vocab: "parry", cat: "3", kind: "choice", word: "parry", ask: "Which definition matches?", answer: 6 },
    { vocab: "pare", cat: "3", kind: "choice", word: "pare", ask: "Which definition matches?", answer: 8 },
    { vocab: "apparel", cat: "3", kind: "choice", word: "apparel", ask: "Which definition matches?", answer: 1 },
    { vocab: "seniority", cat: "3", kind: "choice", word: "seniority", ask: "Which definition matches?", answer: 4 },
    { vocab: "senectitude", cat: "3", kind: "choice", word: "senectitude", ask: "Which definition matches?", answer: 12 },
    { vocab: "subserve", cat: "3", kind: "choice", word: "subserve", ask: "Which definition matches?", answer: 2 },
    { vocab: "reserved", cat: "3", kind: "choice", word: "reserved", ask: "Which definition matches?", answer: 3 },
    { vocab: "servitude", cat: "3", kind: "choice", word: "servitude", ask: "Which definition matches?", answer: 11 },
    { cat: "4", kind: "choice", label: "Flammable and inflammable are opposite in meaning.", text: "Flammable and inflammable are opposite in meaning.", options: ["True","False"], optionStyle: "plain", answer: 1 },
    { cat: "4", kind: "choice", label: "Einstein was a luminary in the field of physics.", text: "Einstein was a luminary in the field of physics.", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { cat: "4", kind: "choice", label: "The noun preserves, as in “fruit preserves,” does…", text: "The noun preserves, as in “fruit preserves,” does not derive from the base SERV-.", options: ["True","False"], optionStyle: "plain", answer: 1 },
    { cat: "4", kind: "choice", label: "Originality and cleverness are characteristic of …", text: "Originality and cleverness are characteristic of an indigenous idea.", options: ["True","False"], optionStyle: "plain", answer: 1 },
    { cat: "4", kind: "choice", label: "The Latin base PAR- also can mean “equal” and “to…", text: "The Latin base PAR- also can mean “equal” and “to give birth.”", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { cat: "4", kind: "choice", label: "Flambeau, a large ornamental candlestick, does no…", text: "Flambeau, a large ornamental candlestick, does not derive from the Latin base FLAM(M)-.", options: ["True","False"], optionStyle: "plain", answer: 1 },
    { cat: "4", kind: "choice", label: "The word lunatic illustrates a once commonly held…", text: "The word lunatic illustrates a once commonly held belief that phases of the moon affect a person’s behavior.", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { cat: "4", kind: "choice", label: "The etymology of the Spanish señor is “older [per…", text: "The etymology of the Spanish señor is “older [person].”", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { cat: "4", kind: "choice", label: "Danger ultimately derives from the DOM(IN)- famil…", text: "Danger ultimately derives from the DOM(IN)- family of words.", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { cat: "4", kind: "choice", label: "The etymological meaning of lucubration is close …", text: "The etymological meaning of lucubration is close to the expression “burning the midnight oil.”", options: ["True","False"], optionStyle: "plain", answer: 0 },
    { vocab: "congenital", cat: "5", kind: "choice", word: "congenital", ask: "Which definition matches?", answer: 7 },
    { vocab: "genre", cat: "5", kind: "choice", word: "genre", ask: "Which definition matches?", answer: 10 },
    { vocab: "disingenuous", cat: "5", kind: "choice", word: "disingenuous", ask: "Which definition matches?", answer: 15 },
    { vocab: "gender", cat: "5", kind: "choice", word: "gender", ask: "Which definition matches?", answer: 8 },
    { vocab: "gentle", cat: "5", kind: "choice", word: "gentle", ask: "Which definition matches?", answer: 5 },
    { vocab: "progeny", cat: "5", kind: "choice", word: "progeny", ask: "Which definition matches?", answer: 1 },
    { vocab: "generalize", cat: "5", kind: "choice", word: "generalize", ask: "Which definition matches?", answer: 13 },
    { vocab: "congenial", cat: "5", kind: "choice", word: "congenial", ask: "Which definition matches?", answer: 0 },
    { vocab: "ingénue", cat: "5", kind: "choice", word: "ingénue", ask: "Which definition matches?", answer: 6 },
    { vocab: "generous", cat: "5", kind: "choice", word: "generous", ask: "Which definition matches?", answer: 4 },
    { vocab: "regenerate", cat: "5", kind: "choice", word: "regenerate", ask: "Which definition matches?", answer: 12 },
    { vocab: "generic products", cat: "5", kind: "choice", word: "generic products", ask: "Which definition matches?", answer: 11 },
    { vocab: "genuine", cat: "5", kind: "choice", word: "genuine", ask: "Which definition matches?", answer: 16 },
    { vocab: "genetics", cat: "5", kind: "choice", word: "genetics", ask: "Which definition matches?", answer: 14 },
    { vocab: "germinate", cat: "5", kind: "choice", word: "germinate", ask: "Which definition matches?", answer: 2 },
    { vocab: "align", cat: "6", kind: "typed", word: "align", ask: "What base does it derive from?", gloss: "LINE", placeholder: "Type the base" },
    { vocab: "pawn", cat: "6", kind: "typed", word: "pawn", ask: "What base does it derive from?", gloss: "PED", placeholder: "Type the base" },
    { vocab: "ingredient", cat: "6", kind: "typed", word: "ingredient", ask: "What base does it derive from?", gloss: "GRAD", placeholder: "Type the base" },
    { vocab: "bonny", cat: "6", kind: "typed", word: "bonny", ask: "What base does it derive from?", gloss: "BENE", placeholder: "Type the base" },
    { vocab: "egalitarian", cat: "6", kind: "typed", word: "egalitarian", ask: "What base does it derive from?", gloss: "EQU", placeholder: "Type the base" },
    { vocab: "regime", cat: "6", kind: "typed", word: "regime", ask: "What base does it derive from?", gloss: "REG", placeholder: "Type the base" },
    { vocab: "damsel", cat: "6", kind: "typed", word: "damsel", ask: "What base does it derive from?", gloss: "DOM", placeholder: "Type the base" },
    { vocab: "enclosure", cat: "6", kind: "typed", word: "enclosure", ask: "What base does it derive from?", gloss: "CLUD", placeholder: "Type the base" },
    { vocab: "grievous", cat: "6", kind: "typed", word: "grievous", ask: "What base does it derive from?", gloss: "GRAV", placeholder: "Type the base" },
    { vocab: "portion", cat: "6", kind: "typed", word: "portion", ask: "What base does it derive from?", gloss: "PART", placeholder: "Type the base" },
    { vocab: "convey", cat: "6", kind: "typed", word: "convey", ask: "What base does it derive from?", gloss: "VI", placeholder: "Type the base" },
    { vocab: "revenue", cat: "6", kind: "typed", word: "revenue", ask: "What base does it derive from?", gloss: "VEN", placeholder: "Type the base" },
    { vocab: "pansy", cat: "6", kind: "typed", word: "pansy", ask: "What base does it derive from?", gloss: "PEND", placeholder: "Type the base" },
    { vocab: "abound", cat: "6", kind: "typed", word: "abound", ask: "What base does it derive from?", gloss: "UND", placeholder: "Type the base" },
    { vocab: "premiere", cat: "6", kind: "typed", word: "premiere", ask: "What base does it derive from?", gloss: "PRIM", placeholder: "Type the base" },
    { cat: "7", kind: "choice", label: "vista / venue / view", ask: "Which word does not belong?", options: ["vista","venue","view"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "comprehension / recompense / compensation", ask: "Which word does not belong?", options: ["comprehension","recompense","compensation"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "priority / precedence / preview", ask: "Which word does not belong?", options: ["priority","precedence","preview"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "ingenuity / complicity / inventiveness", ask: "Which word does not belong?", options: ["ingenuity","complicity","inventiveness"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "pliant / supple / suppliant", ask: "Which word does not belong?", options: ["pliant","supple","suppliant"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "egress / regress / degenerate", ask: "Which word does not belong?", options: ["egress","regress","degenerate"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "redound / unite / combine", ask: "Which word does not belong?", options: ["redound","unite","combine"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "ponderous / pendulous / grave", ask: "Which word does not belong?", options: ["ponderous","pendulous","grave"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "pusillanimous / magnanimous / benevolent", ask: "Which word does not belong?", options: ["pusillanimous","magnanimous","benevolent"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "comply / transgress / observe", ask: "Which word does not belong?", options: ["comply","transgress","observe"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "equivocal / equivalent / similar", ask: "Which word does not belong?", options: ["equivocal","equivalent","similar"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "spite / malice / redoubt", ask: "Which word does not belong?", options: ["spite","malice","redoubt"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "deference / respect / deferment", ask: "Which word does not belong?", options: ["deference","respect","deferment"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "limn / temper / delineate", ask: "Which word does not belong?", options: ["limn","temper","delineate"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "luminous / flagrant / perspicuous", ask: "Which word does not belong?", options: ["luminous","flagrant","perspicuous"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "precede / prevent / preclude", ask: "Which word does not belong?", options: ["precede","prevent","preclude"], optionStyle: "paren", answer: 0, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "accede / assent / proceed", ask: "Which word does not belong?", options: ["accede","assent","proceed"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "secure / detain / fortify", ask: "Which word does not belong?", options: ["secure","detain","fortify"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "improvised / extemporaneous / contretemps", ask: "Which word does not belong?", options: ["improvised","extemporaneous","contretemps"], optionStyle: "paren", answer: 2, answerNote: "doesn’t belong with the other two" },
    { cat: "7", kind: "choice", label: "separate / habitual / individual", ask: "Which word does not belong?", options: ["separate","habitual","individual"], optionStyle: "paren", answer: 1, answerNote: "doesn’t belong with the other two" }
  ]
};
