// Exercise III (Ayers, Lesson IX): an Exercise Deck (Quiz only). Each card
// gives a sentence; the student types the highlighted word's meaning in
// context, judged against the card's definition in context with its
// key-word lists (format as in the Greek decks). The back shows the analysis:
// each part as printed in the workbook, with the shared glossary's full set
// of meanings. Key-word lists approved by the instructor on Oct 5, 2026
// (proposals/exercise-iii-keyword-lists.md).
module.exports = {
  id: "ex3",
  type: "exercise",
  output: "Exercise III Flashcards.html",
  title: "Exercise III Flashcards", // deck name sent to the Sheet
  heading: "Exercise III: Analyze & Define",
  allTitle: "Exercise III",
  instruction: "Analyze the highlighted word, then give its meaning in context.",
  round1: "book",
  legacy: { progressKey: "ex3_progress", nameKey: "ex3_name" },
  cards: [
    { kind: "meaning", word: "SENILE",
      sentence: "The principal doctor was lost in the imbecilities of a <span class=\"target\">senile</span> optimism.",
      cite: "— Lytton Strachey",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"SEN","label":"SEN-"},{"gloss":"-ILE","label":"-ile"}],
      defn: "Pertaining to old age; showing the decline of mental faculties that comes with advanced age.",
      senses: [{"groups":[{"terms":["old age","old","aged","elderly","aging","ageing","advanced age","elder"]}],"star":["doddering","decrepit","dotty","senescent","doting"]},{"groups":[{"terms":["mental","mind","faculties","memory","mentally","thinking","wits"]},{"terms":["decline","declining","failing","deteriorating","weakened","weak","feeble","fading","impaired","deteriorated"]}]}] },
    { kind: "meaning", word: "UNILATERAL",
      sentence: "Ian Smith and his proclamation of UDI (<span class=\"target\">unilateral</span> declaration of independence) for the British territory of Rhodesia in 1965 gave Prime Minister Wilson and the British government a relentless barrage of headaches.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"UNI","label":"uni-"},{"gloss":"LATER","label":"LATER-"},{"gloss":"-AL","label":"-al"}],
      defn: "Affecting or arising from one side only, without the agreement of others.",
      senses: [{"groups":[{"terms":["one","single","only one"]},{"terms":["side","sided","party","nation","country"]}],"star":["one-sided","independent","independently","single-handed","solo"]},{"groups":[{"terms":["without"]},{"terms":["agreement","consent","approval","others"]}]}],
      everyday: ["one","others","without","only one"] },
    { kind: "meaning", word: "GENERATE",
      sentence: "Try as he might, he could not <span class=\"target\">generate</span> any enthusiasm among his fellow councilmen for the issuing of bonds to raise money for new street lights.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"GENER","label":"GENER-"},{"gloss":"-ATE","label":"-ate"}],
      defn: "To produce; to bring into being.",
      senses: [{"groups":[{"terms":["produce","create","make","bring into being","bring about","cause","arouse","rouse","stir up","drum up","muster","raise","spark","build","inspire","evoke","whip up","kindle","awaken"]}]}],
      everyday: ["make","build","raise","cause"] },
    { kind: "meaning", word: "LUMINARY",
      sentence: "An intimacy with Dr. Johnson, the great literary <span class=\"target\">luminary</span> of the day, was the crowning object of his aspiring and somewhat ludicrous ambition.",
      cite: "— Washington Irving",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"LUMIN","label":"LUMIN-"},{"gloss":"-ARY","label":"-ary"}],
      defn: "A person who has achieved eminence in a field, or who inspires and influences others.",
      senses: [{"groups":[{"generic":true,"terms":["person","figure","someone","one","man","woman","writer","author"]},{"terms":["eminent","prominent","famous","celebrated","leading","distinguished","renowned","great","influential","notable","important","inspiring","inspires","influences","respected","acclaimed","noted","illustrious"]}],"star":["celebrity","star","leading light","icon","legend","dignitary","giant","master","notable","authority","expert"]}] },
    { kind: "meaning", word: "TURBULENT",
      sentence: "The <span class=\"target\">turbulent</span> multitude continued roaming and shouting and howling about the city during the day and a part of the night.",
      cite: "— Washington Irving",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"TURB","label":"TURB-"},{"gloss":"-ULENT","label":"-ulent"}],
      defn: "Full of disorder or commotion; unruly, disorderly.",
      senses: [{"groups":[{"terms":["disorder","disorderly","unruly","commotion","chaotic","chaos","wild","rowdy","riotous","tumultuous","tumult","agitated","restless","violent","turmoil","uproar","boisterous","disturbed","out of control","stormy","rebellious","lawless","unrestrained","rambunctious","raucous","noisy"]}]}] },
    { kind: "meaning", word: "AQUATIC",
      sentence: "<span class=\"target\">Aquatic</span> sports are always popular on Florida’s lakes.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"AQU","label":"AQU(A)-"},{"gloss":"-IC","label":"-ic"}],
      defn: "Pertaining to water; carried out in or on water.",
      senses: [{"groups":[{"terms":["water","swimming","lake","sea","marine","in the water","on the water"]}]}] },
    { kind: "meaning", word: "CORPULENT",
      sentence: "He was generally clad in a long, patched livery coat… which bagged loosely around him, having evidently belonged to some <span class=\"target\">corpulent</span> predecessor.",
      cite: "— Dickens",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"CORPOR","label":"CORPOR-, CORP(US)-"},{"gloss":"-ULENT","label":"-ulent"}],
      defn: "Full of body; fat, stout, obese.",
      senses: [{"groups":[{"terms":["fat","stout","obese","overweight","heavy","plump","portly","large","rotund","big","chubby","fleshy","full of body","bulky","hefty","paunchy","round","husky","pudgy","heavyset","large-bodied"]}]}] },
    { kind: "meaning", word: "PRECARIOUS",
      sentence: "The peace we have with us today is as <span class=\"target\">precarious</span> and unsatisfactory as the form of a strip artist with peritonitis.",
      cite: "— E.B. White",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"PREC","label":"PREC-"},{"gloss":"-ARY","label":"-ary (→ i)"},{"gloss":"-OUS","label":"-ous"}],
      defn: "Dependent on chance or circumstance; uncertain, insecure, risky.",
      caution: "Etymologically “pertaining to prayer” — current meaning has drifted well away from the parts. See the Lesson IX slide on etymological vs. current meaning.",
      senses: [{"groups":[{"terms":["uncertain","insecure","risky","unstable","shaky","fragile","unsafe","dangerous","perilous","tenuous","uneasy","chance","unpredictable","delicate","hazardous","unsteady","rocky","dicey","iffy","flimsy","vulnerable","unsure","doubtful","dubious"]}]}] },
    { kind: "meaning", word: "INVOKE",
      sentence: "Please don’t <span class=\"target\">invoke</span> your petty little dogmas in discussion with me; when you think them through, come back and we can have a conversation instead of a button-pushing session.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"IN-into","label":"in-"},{"gloss":"VOC","label":"VOC-, VOK-"}],
      defn: "To call upon; to appeal to or cite in support of an argument.",
      senses: [{"groups":[{"terms":["call upon","call on","appeal to","cite","refer to","bring up","quote","rely on","resort to","summon","call forth","mention","bring in","put forward","reference","use","draw on","fall back on","lean on","point to","raise","call"]}]}],
      everyday: ["use","mention","raise","call"] },
    { kind: "meaning", word: "QUADRILATERAL",
      sentence: "I want you to draw me two <span class=\"target\">quadrilaterals</span>—one a rhombus and one a trapezoid.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"QUADRI","label":"quadri-"},{"gloss":"LATER","label":"LATER-"},{"gloss":"-AL","label":"-al"}],
      defn: "A four-sided figure.",
      senses: [{"groups":[{"terms":["four","4"]},{"terms":["side","sided","sides"]}],"star":["quadrangle","quadrangles","tetragon"]}] },
    { kind: "meaning", word: "GREGARIOUS",
      sentence: "Though this <span class=\"target\">gregarious</span> man is an inveterate joiner and belongs to “every fraternal order in Muncie….”",
      cite: "— Harper’s Magazine",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"GREG","label":"GREG-"},{"gloss":"-ARY","label":"-ary (→ i)"},{"gloss":"-OUS","label":"-ous"}],
      defn: "Fond of the company of others; sociable.",
      senses: [{"groups":[{"terms":["sociable","social","outgoing","friendly","company","companionship","extrovert","extroverted","extravert","people person","fond of others","likes people","convivial","affable","groups","joiner","clubbable","people"]}]}],
      everyday: ["friendly","people","groups","social"] },
    { kind: "meaning", word: "DEFLATED",
      sentence: "She <span class=\"target\">deflated</span> his ego, at least momentarily, by announcing—to everyone within a ten-mile radius—that he had the intellectual range of a baked potato.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"DE","label":"de-"},{"gloss":"FLAT","label":"FLAT-"}],
      defn: "Let the air out of; figuratively, humbled or reduced someone’s pride.",
      senses: [{"groups":[{"terms":["humbled","humiliated","reduced","lowered","diminished","crushed","shrank","shrunk","punctured","belittled","brought down","took down","knocked down","cut down","bruised","wounded","dampened","dented","squashed","shot down","put down","embarrassed","shamed","hurt"]}]},{"groups":[{"terms":["let out","released","let the air out","emptied"]},{"terms":["air"]}]}] },
    { kind: "meaning", word: "RETAINED",
      sentence: "He <span class=\"target\">retained</span> the best lawyer in the state but still lost his case.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"RE","label":"re-"},{"gloss":"TEN","label":"TEN-, TAIN-"}],
      defn: "Hired and kept in one’s service; held onto.",
      senses: [{"groups":[{"terms":["hired","employed","engaged","secured","enlisted","took on","kept","held onto","held","booked","paid","hire","employ","contracted","got","obtained"]}]}],
      everyday: ["kept","held","got","paid"] },
    { kind: "meaning", word: "GENERIC",
      sentence: "Religions differ so much in their accidents that in discussing the religious question we must make it very <span class=\"target\">generic</span> and broad.",
      cite: "— William James",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"GENER","label":"GENER-"},{"gloss":"-IC","label":"-ic"}],
      defn: "Pertaining to a whole class or kind; general, not specific.",
      senses: [{"groups":[{"terms":["general","broad","nonspecific","non-specific","not specific","whole class","universal","all-encompassing","sweeping","inclusive","common","wide-ranging","overall","abstract","vague","unspecific","comprehensive","class","kind","category"]}]}],
      everyday: ["common","kind","class"] },
    { kind: "meaning", word: "INFLAMED",
      sentence: "She was so hooked that even the very thought of him <span class=\"target\">inflamed</span> her passions.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"IN-into","label":"in-"},{"gloss":"FLAM","label":"FLAM(M)-"}],
      defn: "Set on fire; figuratively, aroused or excited intensely.",
      senses: [{"groups":[{"terms":["aroused","excited","stirred","stirred up","kindled","ignited","fired","fired up","heightened","intensified","provoked","sparked","roused","fueled","fuelled","set on fire","set alight","lit","burned","stoked","heated","inflamed","awakened","incited","fanned","flame","fire"]}]}] },
    { kind: "meaning", word: "LUMINOUS",
      sentence: "…the flickering brightness from the inside shining up the chimney and making a <span class=\"target\">luminous</span> mist of the emerging smoke.",
      cite: "— Thomas Hardy",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"LUMIN","label":"LUMIN-"},{"gloss":"-OUS","label":"-ous"}],
      defn: "Full of light; shining, bright.",
      senses: [{"groups":[{"terms":["light","bright","shining","glowing","radiant","brilliant","lit","illuminated","gleaming","luminescent","aglow","shimmering","light-filled","glow","shine","shiny","lustrous","dazzling","beaming","incandescent","lighted"]}]}],
      everyday: ["light"] },
    { kind: "meaning", word: "CONTEMPORARY",
      sentence: "They had not learned the noble dialects of Greece and Rome … and they prized instead a cheap <span class=\"target\">contemporary</span> literature.",
      cite: "— Thoreau",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"CON","label":"con-"},{"gloss":"TEMPOR","label":"TEMPOR-"},{"gloss":"-ARY","label":"-ary"}],
      defn: "Belonging to the same time period; current, modern.",
      senses: [{"groups":[{"terms":["same time","current","modern","present-day","present day","of the time","of the day","of the period","recent","latest","present","up-to-date","contemporaneous","new","time","period","era","age","today","now","day"]}]}],
      everyday: ["new","time","now","day","today","age","period"] },
    { kind: "meaning", word: "SERVILE",
      sentence: "The will of the monarch produced a false and <span class=\"target\">servile</span> unanimity, and no more than two patriots had courage to speak their own sentiments, and those of their country.",
      cite: "— Edward Gibbon",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"SERV","label":"SERV-"},{"gloss":"-ILE","label":"-ile"}],
      defn: "Slavish, submissive; like a servant or slave.",
      senses: [{"groups":[{"terms":["slavish","submissive","servant","slave","obedient","subservient","obsequious","fawning","groveling","grovelling","sycophantic","docile","meek","compliant","cringing","toadying","deferential","spineless","yielding","bootlicking","servant-like","slave-like"]}]}] },
    { kind: "meaning", word: "ENCHANTED",
      sentence: "It would be a gross exaggeration to suggest that I was even for a moment <span class=\"target\">enchanted</span> by our illustrious guest of honor, a pompous ass if I ever met one.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"IN-into","label":"en-","note":"causative"},{"gloss":"CANT","label":"CANT-, CHANT-"}],
      defn: "Put under a spell, as if by a magic song; captivated, charmed. (Used ironically here — the opposite is meant.)",
      caution: "CANT-/CHANT- is not on this course’s assigned base list — confirm with a dictionary.",
      senses: [{"groups":[{"terms":["charmed","captivated","delighted","enthralled","bewitched","spellbound","under a spell","spell","fascinated","entranced","impressed","taken with","smitten","beguiled","dazzled","attracted","pleased","thrilled","mesmerized","mesmerised","won over","bedazzled","magic","enamored","enamoured","infatuated"]}]}] },
    { kind: "meaning", word: "INFER",
      sentence: "You may <span class=\"target\">infer</span> by my painful facial expressions that I consider your horrid rock music to have all the acoustical properties of a major industrial accident.",
      ask: "Meaning in context", placeholder: "Meaning in context",
      parts: [{"gloss":"IN-into","label":"in-"},{"gloss":"FER","label":"FER-"}],
      defn: "To conclude from evidence; to deduce.",
      caution: "FER- is not on this course’s assigned base list — confirm with a dictionary.",
      senses: [{"groups":[{"terms":["conclude","deduce","gather","figure out","reason","surmise","work out","understand","tell","determine","judge","derive","glean","read","see","assume","guess","realize","realise","presume","suppose","sense","pick up","evidence"]}]}],
      everyday: ["tell","see","read","understand","sense","guess","assume","suppose"] }
  ]
};
