// Shared glossary: every base, prefix and suffix used in the decks, once,
// with its forms and its full set of meanings. Decks point to entries by key
// instead of repeating the meanings, so every deck shows the same wording.
// Instructor's ruling (Oct 5, 2026): the Latin Roots meanings are used across
// the board, except IN- (directional) adds "upon" and GENER- is
// "race, kind, origin". Each meaning is a separate item (a base's meanings
// are distinct, not alternatives).
// source: the deck the wording comes from.
// wording: where the meanings' wording comes from (approved Oct 7, 2026): book,
// workbook, answer key, instructor, dictionary, or "Claude, unchecked". The
// Latin Roots meanings were written by Claude and are not yet checked against
// the book; BI-, ANIM- and ANN- are the Lesson IX workbook's printed meanings;
// -ARY's two meanings were confirmed by the instructor; the Greek elements are
// the book's (bishop, devil) or the Online Etymology Dictionary's.
module.exports = {
  // ---- Latin Roots: bases ----
  "ALIEN": { forms: "ALIEN-", kind: "base", meanings: ["belonging to another","foreign"], examples: "alienate, alien, inalienable", source: "Latin Roots", wording: "Claude, unchecked" },
  "ART": { forms: "ART-", kind: "base", meanings: ["skill","craft"], examples: "artisan, artificial, artifact", source: "Latin Roots", wording: "Claude, unchecked" },
  "CED": { forms: "CED-, CESS-", kind: "base", meanings: ["to go","yield","withdraw"], examples: "proceed, recede, concession, access", source: "Latin Roots", wording: "Claude, unchecked" },
  "CLUD": { forms: "CLUD-, CLUS-, [CLOS-]", kind: "base", meanings: ["to close","shut"], examples: "include, exclude, conclusion, closure", source: "Latin Roots", wording: "Claude, unchecked" },
  "CRUC": { forms: "CRUC-", kind: "base", meanings: ["cross"], examples: "crucial, crucifix, excruciating", source: "Latin Roots", wording: "Claude, unchecked" },
  "CUR": { forms: "CUR(R)-, CURS- [COURS-], [COR(S)-]", kind: "base", meanings: ["to run"], examples: "current, cursive, excursion, course", source: "Latin Roots", wording: "Claude, unchecked" },
  "DUC": { forms: "DUC-, DUCT-", kind: "base", meanings: ["to lead"], examples: "conduct, induce, deduction", source: "Latin Roots", wording: "Claude, unchecked" },
  "FAC": { forms: "FAC- [FIC-]", kind: "base", meanings: ["to make","do"], examples: "factory, manufacture, fiction, deficient", source: "Latin Roots", wording: "Claude, unchecked" },
  "FIN": { forms: "FIN-", kind: "base", meanings: ["end","boundary"], examples: "finish, final, infinite", source: "Latin Roots", wording: "Claude, unchecked" },
  "FIRM": { forms: "FIRM-", kind: "base", meanings: ["strong","firm"], examples: "confirm, affirm, infirmary", source: "Latin Roots", wording: "Claude, unchecked" },
  "FORT": { forms: "FORT-", kind: "base", meanings: ["strong","brave"], examples: "fortify, fortress, effort", source: "Latin Roots", wording: "Claude, unchecked" },
  "GRAD": { forms: "GRAD-, GRESS-", kind: "base", meanings: ["to step","go","walk"], examples: "graduate, progress, regression", source: "Latin Roots", wording: "Claude, unchecked" },
  "GRAND": { forms: "GRAND-", kind: "base", meanings: ["great","large"], examples: "grandeur, aggrandize, grandiose", source: "Latin Roots", wording: "Claude, unchecked" },
  "GRAV": { forms: "GRAV- [GRIEV-]", kind: "base", meanings: ["heavy"], examples: "gravity, aggravate, grieve", source: "Latin Roots", wording: "Claude, unchecked" },
  "GREG": { forms: "GREG-", kind: "base", meanings: ["flock","group"], examples: "gregarious, segregate, congregate", source: "Latin Roots", wording: "Claude, unchecked" },
  "HAB": { forms: "HAB-, AB- [HIB-]", kind: "base", meanings: ["to have","hold"], examples: "habit, exhibit, inhibit, prohibit", source: "Latin Roots", wording: "Claude, unchecked" },
  "JUDIC": { forms: "JUDIC-", kind: "base", meanings: ["to judge"], examples: "judicial, prejudice, adjudicate", source: "Latin Roots", wording: "Claude, unchecked" },
  "JUR": { forms: "JUR-, JUST-", kind: "base", meanings: ["law","right","to swear"], examples: "jury, justice, jurisdiction, perjury", source: "Latin Roots", wording: "Claude, unchecked" },
  "LEV": { forms: "LEV-", kind: "base", meanings: ["light (weight)","to lift"], examples: "elevate, levity, alleviate", source: "Latin Roots", wording: "Claude, unchecked" },
  "LINE": { forms: "LINE- [LIGN-]", kind: "base", meanings: ["line","thread"], examples: "linear, delineate, align", source: "Latin Roots", wording: "Claude, unchecked" },
  "LIMIN": { forms: "LIMIN-", kind: "base", meanings: ["threshold"], examples: "preliminary, subliminal, eliminate", source: "Latin Roots", wording: "Claude, unchecked" },
  "LOC": { forms: "LOC-", kind: "base", meanings: ["place"], examples: "locate, dislocate, allocate", source: "Latin Roots", wording: "Claude, unchecked" },
  "LOQU": { forms: "LOQU-, LOCUT-", kind: "base", meanings: ["to speak","talk"], examples: "eloquent, loquacious, elocution", source: "Latin Roots", wording: "Claude, unchecked" },
  "LUD": { forms: "LUD-, LUS-", kind: "base", meanings: ["to play"], examples: "illusion, allude, ludicrous", source: "Latin Roots", wording: "Claude, unchecked" },
  "NIHIL": { forms: "NIHIL-", kind: "base", meanings: ["nothing"], examples: "nihilism, annihilate", source: "Latin Roots", wording: "Claude, unchecked" },
  "NOMIN": { forms: "NOMIN-", kind: "base", meanings: ["name"], examples: "nominate, denomination, nominal", source: "Latin Roots", wording: "Claude, unchecked" },
  "NUL": { forms: "NUL(L)-", kind: "base", meanings: ["none","not any"], examples: "null, nullify, annul", source: "Latin Roots", wording: "Claude, unchecked" },
  "PART": { forms: "PART-", kind: "base", meanings: ["part","share"], examples: "partial, participate, partition", source: "Latin Roots", wording: "Claude, unchecked" },
  "PED": { forms: "PED-", kind: "base", meanings: ["foot"], examples: "pedal, pedestrian, expedition", source: "Latin Roots", wording: "Claude, unchecked" },
  "PEND": { forms: "PEND-, PENS-", kind: "base", meanings: ["to hang","weigh","pay"], examples: "suspend, pension, compensate", source: "Latin Roots", wording: "Claude, unchecked" },
  "PLE": { forms: "PLE-, PLET-, PLEN-", kind: "base", meanings: ["to fill","full"], examples: "complete, deplete, plenty", source: "Latin Roots", wording: "Claude, unchecked" },
  "PREC": { forms: "PREC-", kind: "base", meanings: ["to pray","ask","beg"], examples: "deprecate, imprecation, precarious", source: "Latin Roots", wording: "Claude, unchecked" },
  "PULS": { forms: "PULS-", kind: "base", meanings: ["to drive","push","beat"], examples: "pulse, repulsive, compulsion", source: "Latin Roots", wording: "Claude, unchecked" },
  "PUNG": { forms: "PUNG-, PUNCT-", kind: "base", meanings: ["to prick","pierce","point"], examples: "pungent, punctual, puncture", source: "Latin Roots", wording: "Claude, unchecked" },
  "SACR": { forms: "SACR- [SECR-]", kind: "base", meanings: ["sacred","holy"], examples: "sacred, sacrifice, consecrate, sacrilege", source: "Latin Roots", wording: "Claude, unchecked" },
  "SANCT": { forms: "SANCT-", kind: "base", meanings: ["holy","inviolable"], examples: "sanctuary, sanction, sanctify", source: "Latin Roots", wording: "Claude, unchecked" },
  "SED": { forms: "SED-", kind: "base", meanings: ["to sit","settle"], examples: "sedentary, sediment, reside", source: "Latin Roots", wording: "Claude, unchecked" },
  "SENT": { forms: "SENT-, SENS-", kind: "base", meanings: ["to feel","perceive"], examples: "sentiment, sensation, consent", source: "Latin Roots", wording: "Claude, unchecked" },
  "SPEC": { forms: "SPEC-, (SPIC-), SPECT-", kind: "base", meanings: ["to look","see"], examples: "spectacle, inspect, conspicuous", source: "Latin Roots", wording: "Claude, unchecked" },
  "SPIR": { forms: "SPIR-", kind: "base", meanings: ["to breathe"], examples: "inspire, respire, conspire", source: "Latin Roots", wording: "Claude, unchecked" },
  "TRUD": { forms: "TRUD-, TRUS-", kind: "base", meanings: ["to push","thrust"], examples: "intrude, protrude, obtrusive", source: "Latin Roots", wording: "Claude, unchecked" },
  "TURB": { forms: "TURB-", kind: "base", meanings: ["to disturb","confuse","crowd"], examples: "turbulent, disturb, perturb", source: "Latin Roots", wording: "Claude, unchecked" },
  "UND": { forms: "UND- [OUND-]", kind: "base", meanings: ["wave"], examples: "undulate, abound, redundant", source: "Latin Roots", wording: "Claude, unchecked" },
  "VEN": { forms: "VEN-, VENT-, [VENU-]", kind: "base", meanings: ["to come"], examples: "convene, prevent, venue", source: "Latin Roots", wording: "Claude, unchecked" },
  "VERB": { forms: "VERB-", kind: "base", meanings: ["word"], examples: "verbal, verbose, proverb", source: "Latin Roots", wording: "Claude, unchecked" },
  "VERT": { forms: "VERT-, VERS-", kind: "base", meanings: ["to turn"], examples: "convert, reverse, invert", source: "Latin Roots", wording: "Claude, unchecked" },
  "VEST": { forms: "VEST-", kind: "base", meanings: ["clothing"], examples: "invest, divest, vestment", source: "Latin Roots", wording: "Claude, unchecked" },
  "VI": { forms: "VI(A)-", kind: "base", meanings: ["way","road"], examples: "via, deviate, viaduct", source: "Latin Roots", wording: "Claude, unchecked" },
  "VID": { forms: "VID-, VIS- [VIEW-]", kind: "base", meanings: ["to see"], examples: "video, visible, review", source: "Latin Roots", wording: "Claude, unchecked" },
  "VOC": { forms: "VOC-, VOK-", kind: "base", meanings: ["to call","voice"], examples: "vocal, vocation, invoke", source: "Latin Roots", wording: "Claude, unchecked" },

  // ---- Latin Roots: prefixes ----
  "AB": { forms: "AB-, A-, ABS-", kind: "prefix", meanings: ["away from","from"], examples: "absent, avert, abstain", source: "Latin Roots", wording: "Claude, unchecked" },
  "AD": { forms: "AD-, AC-", kind: "prefix", meanings: ["to","toward"], examples: "adhere, accept, advance", source: "Latin Roots", wording: "Claude, unchecked" },
  "AMBI": { forms: "AMBI-", kind: "prefix", meanings: ["both","around"], examples: "ambidextrous, ambiguous", source: "Latin Roots", wording: "Claude, unchecked" },
  "ANTE": { forms: "ANTE-", kind: "prefix", meanings: ["before"], examples: "antebellum, anteroom, antecedent", source: "Latin Roots", wording: "Claude, unchecked" },
  "CIRCUM": { forms: "CIRCUM-", kind: "prefix", meanings: ["around"], examples: "circumference, circumvent", source: "Latin Roots", wording: "Claude, unchecked" },
  "CON": { forms: "CON-, COM-, CO-", kind: "prefix", meanings: ["with","together"], examples: "connect, combine, cooperate", source: "Latin Roots", wording: "Claude, unchecked" },
  "CONTRA": { forms: "CONTRA-, CONTRO-, COUNTER-", kind: "prefix", meanings: ["against"], examples: "contradict, controversy, counteract", source: "Latin Roots", wording: "Claude, unchecked" },
  "DE": { forms: "DE-", kind: "prefix", meanings: ["down","away","reversal"], examples: "descend, depart, devalue", source: "Latin Roots", wording: "Claude, unchecked" },
  "DIS": { forms: "DIS-, DI-, DIF-", kind: "prefix", meanings: ["apart","not","away"], examples: "disagree, divert, differ", source: "Latin Roots", wording: "Claude, unchecked" },
  "EX": { forms: "EX-, E-, EF-", kind: "prefix", meanings: ["out","out of"], examples: "exit, emit, efface", source: "Latin Roots", wording: "Claude, unchecked" },
  "EXTRA": { forms: "EXTRA-, EXTRO-", kind: "prefix", meanings: ["outside","beyond"], examples: "extraordinary, extrovert, extraterrestrial", source: "Latin Roots", wording: "Claude, unchecked" },
  "IN-not": { forms: "IN-, IM- [IG- before n] (negative)", kind: "prefix", meanings: ["not","without"], examples: "inactive, impossible, ignoble", source: "Latin Roots", wording: "Claude, unchecked" },
  "IN-into": { forms: "IN-, IM-, [EN-], [EM-] (directional)", kind: "prefix", meanings: ["into","in","on","upon"], examples: "inject, immerse, enclose, empower", source: "Latin Roots", wording: "Claude, unchecked" },
  "INFRA": { forms: "INFRA-", kind: "prefix", meanings: ["below","beneath"], examples: "infrastructure, infrared", source: "Latin Roots", wording: "Claude, unchecked" },
  "INTER": { forms: "INTER-", kind: "prefix", meanings: ["between","among"], examples: "interact, international, intersect", source: "Latin Roots", wording: "Claude, unchecked" },
  "INTRA": { forms: "INTRA-, INTRO-", kind: "prefix", meanings: ["within","inside"], examples: "intramural, introvert, introspect", source: "Latin Roots", wording: "Claude, unchecked" },
  "NON": { forms: "NON-", kind: "prefix", meanings: ["not"], examples: "nonsense, nonexistent, nonfiction", source: "Latin Roots", wording: "Claude, unchecked" },
  "OB": { forms: "OB-", kind: "prefix", meanings: ["against","toward","in the way"], examples: "object, obstruct, obstacle", source: "Latin Roots", wording: "Claude, unchecked" },
  "PER": { forms: "PER-", kind: "prefix", meanings: ["through","thoroughly"], examples: "permeate, perceive, persist", source: "Latin Roots", wording: "Claude, unchecked" },
  "POST": { forms: "POST-", kind: "prefix", meanings: ["after"], examples: "postpone, posterity, postwar", source: "Latin Roots", wording: "Claude, unchecked" },
  "PRE": { forms: "PRE-", kind: "prefix", meanings: ["before"], examples: "predict, prevent, precede", source: "Latin Roots", wording: "Claude, unchecked" },
  "PRO": { forms: "PRO-", kind: "prefix", meanings: ["forward","for","in favor of"], examples: "proceed, promote, propose", source: "Latin Roots", wording: "Claude, unchecked" },
  "RE": { forms: "RE-, RED- (before vowels)", kind: "prefix", meanings: ["back","again"], examples: "return, redeem, react", source: "Latin Roots", wording: "Claude, unchecked" },
  "RETRO": { forms: "RETRO-", kind: "prefix", meanings: ["backward"], examples: "retrospect, retroactive, retrograde", source: "Latin Roots", wording: "Claude, unchecked" },
  "SE": { forms: "SE-, SED- (before vowels)", kind: "prefix", meanings: ["apart","aside","without"], examples: "separate, secede, sedition", source: "Latin Roots", wording: "Claude, unchecked" },
  "SUB": { forms: "SUB-, SUS-, SUC-", kind: "prefix", meanings: ["under","below"], examples: "submarine, suspend, succeed", source: "Latin Roots", wording: "Claude, unchecked" },
  "SUPER": { forms: "SUPER- [SUR-]", kind: "prefix", meanings: ["above","over"], examples: "superior, surpass, superimpose", source: "Latin Roots", wording: "Claude, unchecked" },
  "TRANS": { forms: "TRANS-, TRAN-, TRA-", kind: "prefix", meanings: ["across","through","beyond"], examples: "transmit, transcend, traverse", source: "Latin Roots", wording: "Claude, unchecked" },
  "ULTRA": { forms: "ULTRA-", kind: "prefix", meanings: ["beyond","excessively"], examples: "ultraviolet, ultrasound, ultramodern", source: "Latin Roots", wording: "Claude, unchecked" },

  // ---- Other Latin bases (Exercise III and Lesson IX) ----
  "SEN": { forms: "SEN-", kind: "base", meanings: ["old"], source: "Exercise III", wording: "Claude, unchecked" },
  "LATER": { forms: "LATER-", kind: "base", meanings: ["side"], source: "Exercise III", wording: "Claude, unchecked" },
  "GENER": { forms: "GENER-", kind: "base", meanings: ["race", "kind", "origin"], note: "related to GEN-, \u201cto give birth to, produce\u201d", source: "Exercise III", wording: "instructor" },
  "LUMIN": { forms: "LUMIN-", kind: "base", meanings: ["to shine", "light"], source: "Exercise III", wording: "Claude, unchecked" },
  "AQU": { forms: "AQU(A)-", kind: "base", meanings: ["water"], source: "Exercise III", wording: "Claude, unchecked" },
  "CORPOR": { forms: "CORPOR-, CORP(US)-", kind: "base", meanings: ["body"], source: "Exercise III", wording: "Claude, unchecked" },
  "FLAT": { forms: "FLAT-", kind: "base", meanings: ["to blow"], source: "Exercise III", wording: "Claude, unchecked" },
  "TEN": { forms: "TEN-, TAIN-", kind: "base", meanings: ["to hold"], source: "Exercise III", wording: "Claude, unchecked" },
  "FLAM": { forms: "FLAM(M)-", kind: "base", meanings: ["flame"], source: "Exercise III", wording: "Claude, unchecked" },
  "TEMPOR": { forms: "TEMPOR-", kind: "base", meanings: ["time"], source: "Exercise III", wording: "Claude, unchecked" },
  "SERV": { forms: "SERV-", kind: "base", meanings: ["to serve"], source: "Exercise III", wording: "Claude, unchecked" },
  "CANT": { forms: "CANT-, CHANT-", kind: "base", meanings: ["to sing"], source: "Exercise III", wording: "Claude, unchecked" },
  "FER": { forms: "FER-", kind: "base", meanings: ["to carry", "bear"], source: "Exercise III", wording: "Claude, unchecked" },
  "BENE": { forms: "BENE-, BON-", kind: "base", meanings: ["good", "well"], source: "Lesson IX", wording: "Claude, unchecked" },
  "EQU": { forms: "EQU-, (IQU-)", kind: "base", meanings: ["equal"], source: "Lesson IX", wording: "Claude, unchecked" },
  "REG": { forms: "REG-, (RIG-), RECT-", kind: "base", meanings: ["to rule", "straight"], source: "Lesson IX", wording: "Claude, unchecked" },
  "DOM": { forms: "DOM(IN)-", kind: "base", meanings: ["house", "master"], source: "Lesson IX", wording: "Claude, unchecked" },
  "PRIM": { forms: "PRIM-", kind: "base", meanings: ["first"], source: "Lesson IX", wording: "Claude, unchecked" },
  "ANIM": { forms: "ANIM-", kind: "base", meanings: ["mind", "feeling", "life"], source: "Lesson IX", wording: "workbook" },
  "ANN": { forms: "ANN-", kind: "base", meanings: ["year"], source: "Lesson IX", wording: "workbook" },

  // ---- Other Latin prefixes (Exercise III, Lesson IX) ----
  "UNI": { forms: "UNI-", kind: "prefix", meanings: ["one"], source: "Exercise III", wording: "Claude, unchecked" },
  "QUADRI": { forms: "QUADRI-", kind: "prefix", meanings: ["four"], source: "Exercise III", wording: "Claude, unchecked" },
  "BI": { forms: "BI-", kind: "prefix", meanings: ["two", "twice"], source: "Lesson IX", wording: "workbook" },

  // ---- Suffixes (Exercise III) ----
  "-ILE": { forms: "-ILE", kind: "suffix", meanings: ["pertaining to", "like"], source: "Exercise III", wording: "Claude, unchecked" },
  "-AL": { forms: "-AL", kind: "suffix", meanings: ["pertaining to"], source: "Exercise III", wording: "Claude, unchecked" },
  "-ATE": { forms: "-ATE", kind: "suffix", meanings: ["to make", "do"], source: "Exercise III", wording: "Claude, unchecked" },
  // Exercise III gives -ary two meanings: "one connected with" (luminary)
  // and "pertaining to" (contemporary, precarious, gregarious). The instructor
  // confirmed both meanings on 2026-10-05.
  "-ARY": { forms: "-ARY", kind: "suffix", meanings: ["pertaining to", "one connected with"], source: "Exercise III", wording: "instructor" },
  "-ULENT": { forms: "-ULENT", kind: "suffix", meanings: ["full of", "disposed to"], source: "Exercise III", wording: "Claude, unchecked" },
  "-IC": { forms: "-IC", kind: "suffix", meanings: ["pertaining to"], source: "Exercise III", wording: "Claude, unchecked" },
  "-OUS": { forms: "-OUS", kind: "suffix", meanings: ["full of"], source: "Exercise III", wording: "Claude, unchecked" },

  // ---- Greek (Greek Introduction Exercise) ----
  "g:epi": { forms: "epi-", kind: "greek", meanings: ["over"], source: "Greek Introduction Exercise", wording: "book" },
  "g:skopos": { forms: "skopos", kind: "greek", meanings: ["watcher"], source: "Greek Introduction Exercise", wording: "book" },
  "g:blas": { forms: "blas-", kind: "greek", meanings: ["origin uncertain; perhaps \u201charmful\u201d"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:pheme": { forms: "ph\u0113m\u0113", kind: "greek", meanings: ["utterance", "speech"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:kata": { forms: "kata-", kind: "greek", meanings: ["down"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:hedra": { forms: "hedra", kind: "greek", meanings: ["seat"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:dia": { forms: "dia-", kind: "greek", meanings: ["across"], source: "Greek Introduction Exercise", wording: "book" },
  "g:ballein": { forms: "ballein", kind: "greek", meanings: ["to throw"], source: "Greek Introduction Exercise", wording: "book" },
  "g:gramma": { forms: "gramma", kind: "greek", meanings: ["letter"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:para": { forms: "para-", kind: "greek", meanings: ["beside"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:lyein": { forms: "lyein", kind: "greek", meanings: ["to loosen"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:bole": { forms: "bol\u0113", kind: "greek", meanings: ["a throwing"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:presbys": { forms: "presbys", kind: "greek", meanings: ["old"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:-teros": { forms: "-teros", kind: "greek", meanings: ["-er (comparative)"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:histor": { forms: "hist\u014dr", kind: "greek", meanings: ["knowing", "learned", "a witness"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:eleos": { forms: "eleos", kind: "greek", meanings: ["pity", "mercy"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:kyrios": { forms: "kyrios", kind: "greek", meanings: ["lord"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:xeros": { forms: "x\u0113ros", kind: "greek", meanings: ["dry"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:pous": { forms: "pous, podos", kind: "greek", meanings: ["foot"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:phainesthai": { forms: "phainesthai", kind: "greek", meanings: ["to appear"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:phren": { forms: "phr\u0113n", kind: "greek", meanings: ["mind"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:-itis": { forms: "-itis", kind: "greek", meanings: ["inflammation"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:lampein": { forms: "lampein", kind: "greek", meanings: ["to shine"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:glykys": { forms: "glykys", kind: "greek", meanings: ["sweet"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:rhiza": { forms: "rhiza", kind: "greek", meanings: ["root"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:platys": { forms: "platys", kind: "greek", meanings: ["broad"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:kheir": { forms: "kheir", kind: "greek", meanings: ["hand"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:ergon": { forms: "ergon", kind: "greek", meanings: ["work"], source: "Greek Introduction Exercise", wording: "dictionary" },
  "g:trekhein": { forms: "trekhein", kind: "greek", meanings: ["to run"], source: "Greek Introduction Exercise", wording: "dictionary" }
};
